title: Town of Saviom Auto-Battler
description: Documentazione del progetto ToSAB
lang: it
url: "https://zanetti33.github.io"
baseurl: "/PPS-24-ToSAB"
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Torna su"

plugins:
  - jekyll-remote-theme

mermaid:
  version: "10.6.1"